db:
  image: postgres:9.4.1
  expose:
    - "5432"

web:
  build: .
  command: bundle exec puma -t 5:5 -p `PORT
  env_file: config/application.yml
  environment:
    - PORT=80
    - RACK_ENV=docker
  ports:
    - "5000:80"
  links:
    - db
  volumes:
    - .:/app
