  development:
    access_key_id: Figaro.env.aws_key
    secret_access_key: Figaro.env.aws_secret

  production:
    access_key_id: Figaro.env.aws_key
    secret_access_key: Figaro.env.aws_secret

  test:
    access_key_id: Figaro.env.aws_key
    secret_access_key: Figaro.env.aws_secret
